### ISSUE TITLE
EPIC : Inventaire des projets

### ISSUE THREAD

**Issue by NoeBerdoz** [antistatique/citadel#107]
### 🗃️ Issues
- [ ]  Inventaire des projets actifs, inactifs et archivés

Filtre des projet selon les états suivants :
- [ ] Navette(s), Personne(s), Hosting(s), Status, Technologie(s), Specs
- [ ] Outdated (une version d’au moins une technologie est outdated)
- [ ] Domaine expiré et domaine proche de l’expiration
- [ ] Facturation manquante
- [ ] Par date de publication, date de release;
- [ ] Most outdated (les projets ayant une technologie outdated avec le plus de jours
outdated depuis sa dernière version)
- [ ] Recherche textuel des projets par leur titres

### ✅ DOD
- [ ] Listing des projets
- [ ] Fonctionnement des différents filtres
