### ISSUE TITLE
[31] EPIC : Membres et Navettes

### ISSUE THREAD

**Issue by NoeBerdoz** [antistatique/citadel#108]
### 🗃️ Issues
- [x] #127 CRUD des membres
- [x] #126 CRUD des navettes
- [x] #128 Attribution d'un projet à une navette
- [x] #129 Attribution d'un projet à des membres
- [x] #131 Attribution de rôle décisionnel aux membres
- [ ] #235 Gestion des mots de passes utilisateurs

### ✅ DOD
- [x] Possibilité de créer, éditer, supprimer des membres et des navettes
- [x] Lors de la création d'un projet, possibilité d'attribuer une navette/membres au projet.
