### ISSUE TITLE
EPIC : Technologies

### ISSUE THREAD

**Issue by NoeBerdoz** [antistatique/citadel#109]
Information concernant le niveau d'update d'un projet
### 🗃️ Issues
- [ ] Présenter les updates disponibles
- [ ] Priorité de l'update
- [ ] Définition de plusieurs technologies par projet (Feature activable/désactivable) 
- [ ] Présentation du nombre de jours en état outdated

### ✅ DOD
- [ ] Le listing des projets démontre si un projet est outdated ou non
- [ ] Les détail du projet démontres les updates disponible et leurs priorités
- [ ] CLors de la création/édition d'un projet, un élément dans le formulaire permet d'ajouter/retirer/éditer la/les technologies du projet
- [ ] Une information présente dans le listing/détail présente depuis combien de jours le projet est outdated
