### ISSUE TITLE
EPIC : Security

### ISSUE THREAD

**Issue by NoeBerdoz** [antistatique/citadel#110]
### 🗃️ Issues
- [ ] Ajouter une feature "Security Check" liée à l'API Dependabot de GitHub

### ✅ DOD
- [ ] Présentation d'un niveau de sécurité du projet dans le listing/détail du projet
- [ ] Notification en cas d'apparition de failles
