### ISSUE TITLE
EPIC : Hosting

### ISSUE THREAD

**Issue by NoeBerdoz** [antistatique/citadel#111]
### 🗃️ Issues
- [ ] CRUD Hosting
- [ ] Définition de un/plusieurs hostings pour un projet
- [ ] Synchronisation des Specs du projet et de leurs versions si le hosting est chez Alwaysdata

### ✅ DOD
- [ ] Possibilité d'ajouter, éditer, supprimer un hosting
- [ ] Attribution de un ou plusieurs hosting sur un projet
- [ ] Synchronisation Alwaysdata
