### ISSUE TITLE
EPIC : Contrat de maintenance

### ISSUE THREAD

**Issue by NoeBerdoz** [antistatique/citadel#113]
### 🗃️ Issues
- [ ] Ajout de un ou plusieurs contrats de maintenance à un projet

Le contrat de maintenance dispose des valeurs suivantes :
- [ ] Date de signature (YYYY-MM-DD)
- [ ] Type de contrat (maintenance annuel / support - cette liste est non exhaustive)
- [ ] Lien vers le contrat sur le serveur interne (HAL9000)

### ✅ DOD
- [ ] Les détails du projet présente ses contrats de maintenance
- [ ] L'implémentation évite les doublon avec les outils externes
- [ ] L'implémentation est succincte et renvoie vers les différents outils externes (Harvest)
