### ISSUE TITLE
EPIC : Facturation récurrente

### ISSUE THREAD

**Issue by NoeBerdoz** [antistatique/citadel#114]
### 🗃️ Issues
- [ ] Création de facturation récurrente pour le Hosting
- [ ] Création de facturation récurrente pour la Maintenance annuelle
- [ ] Création de facturation récurrente pour le Nom de domaine
- [ ] Attribution de factures récurrentes à un projet

### ✅ DOD
- [ ] Possibilité d'ajouter une ou plusieurs factures récurrentes à un projet
- [ ] Une facturation récurrente est définie par un identifiant Harvest du client pour lien vers le listing des factures dans Harvest ainsi que du lien vers le template de facture récurrent du client concerné
