### ISSUE TITLE
EPIC : Système de notes

### ISSUE THREAD

**Issue by NoeBerdoz** [antistatique/citadel#115]
### 🗃️ Issues
Notes "en vrac" liées à un projet afin d'annoter les points importants liés au projet
Le système de notes doit contenir les éléments suivants :
- [ ] Description
- [ ] Date de création
- [ ] Auteur
- [ ] Status (standard, warning, critical)

### ✅ DOD
- [ ] Le détail d'un projet présente une partie Notes où les utilisateurs peuvent ajouter, éditer, supprimer une note
- [ ] Un élément visuel définit démontre le status de la note (standard, warning, critical)
