### ISSUE TITLE
EPIC : Notifications

### ISSUE THREAD

**Issue by NoeBerdoz** [antistatique/citadel#116]
### 🗃️ Issues
Système de notifications automatique par mail
- [ ] Envois d'un email lors de la création d'un repository sur GitHub (GitHub Hooks API)
- [ ] Attribution des membres aux notifications.

### ✅ DOD
- [ ] L'email est envoyé à un groupe de membre spécifié
- [ ] L'email présente un lien renvoyant vers la création d'un projet sur la plateforme Citadel
