### ISSUE TITLE
[13] EPIC : Authentication

### ISSUE THREAD

**Issue by WengerK** [antistatique/citadel#118]
### 🗃️ Issues

- [x] #121 Système d'authentification user/password
- [x] #122 Authentification Google auth (@antistatique only)

### ✅ DOD

- [x] Possibilité de se connecter avec un compte (entity User) username/password
- [x] Possibilité de se connecter avec un compte @antistatique via Google (bouton spécifique)

**Comment by gido** [comment]
https://symfony.com/doc/current/security/form_login_setup.html 😀
