### ISSUE TITLE
EPIC : Dependencies Managements

### ISSUE THREAD

**Issue by gido** [antistatique/citadel#303]
### 🗃️ Issues
- [ ] 1. Import and sync all releases per technologies
- [ ] 2.1 Extract the current project technology version and update `Dependency` entity.
      * Read / Write the `Dependency#config`
- [ ] 3. Write the cronjob: Check if there is some "Available release" for a project technology

### ✅ DOD
- [ ] Do that
- [ ] Can achieve this

**Comment by gido** [comment]
**Insipirations:**
 * https://github.com/antistatique/citadel/pull/275
 * https://github.com/antistatique/citadel/blob/master/src/Crawler/GithubCrawler.php
